name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and run deploy script
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          npm install -g markdown-to-html-cli @akashic/akashic-cli
          ./.github/scripts/deploy.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}